//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppAPI.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ArticleUser
    {
        public int ArticleId { get; set; }
        public string ArticleTitle { get; set; }
        public string ArticleSubtitle { get; set; }
        public string ArticleTags { get; set; }
        public string ArticleDes { get; set; }
    }
}
